name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  GRADLE_VERSION: "8.7"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Bootstrap Gradle (không cần wrapper sẵn trong repo)
      - name: Download Gradle ${{ env.GRADLE_VERSION }}
        run: |
          set -e
          curl -sSLo gradle-${{ env.GRADLE_VERSION }}-bin.zip \
            "https://services.gradle.org/distributions/gradle-${{ env.GRADLE_VERSION }}-bin.zip" --retry 5 --retry-all-errors
          unzip -q gradle-${{ env.GRADLE_VERSION }}-bin.zip

      - name: Generate Gradle Wrapper
        run: |
          ./gradle-${{ env.GRADLE_VERSION }}/bin/gradle wrapper --gradle-_
