name: Android CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true           # cần nếu Dobby dùng git submodule
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install CMake & NDK
        run: |
          sdkmanager --install "cmake;3.22.1" "ndk;26.1.10909125"
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/26.1.10909125" >> $GITHUB_ENV

      # Repo chưa có Wrapper -> sinh wrapper trước, rồi mới validate
      - name: Generate Gradle Wrapper (8.7)
        uses: gradle/gradle-build-action@v3
        with:
          arguments: wrapper --gradle-version 8.7

      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: MyHookModule-debug-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
