name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  GRADLE_VERSION: "8.7"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
  submodules: true

    - name: Install CMake & NDK
  run: |
    sdkmanager --install "cmake;3.22.1" "ndk;26.1.10909125"
    echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/26.1.10909125" >> $GITHUB_ENV

      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Tải Gradle 8.7 (1 dòng URL, có retry)
      - name: Download Gradle ${{ env.GRADLE_VERSION }}
        run: |
          set -e
          curl -sSLo gradle-${{ env.GRADLE_VERSION }}-bin.zip "https://services.gradle.org/distributions/gradle-${{ env.GRADLE_VERSION }}-bin.zip" --retry 5 --retry-all-errors
          unzip -q gradle-${{ env.GRADLE_VERSION }}-bin.zip

      # Sinh wrapper "thật" bằng Gradle vừa tải
      - name: Generate Gradle Wrapper
        run: |
          ./gradle-${{ env.GRADLE_VERSION }}/bin/gradle wrapper --gradle-version ${{ env.GRADLE_VERSION }}
          chmod +x gradlew
          ./gradlew --version
          ls -la gradle/wrapper

      - name: Build with Gradle (debug)
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MyHookModule-APK
          path: app/build/outputs/apk/debug/app-debug.apk
